function cleanupEntry()

    table = subject.Subject();

    entry_input1 = struct(...
        'subject_id', 'm3', ...
        'dob', '2020-08-05', ...
        'sex', 'U', ...
        'breeding_pair', '', ...
        'species', 'mouse', ...
        'mark_type', 'ear', ...
        'mark', '', ...
        'source_name', 'homemade', ...
        'strain_name', 'jRGECO', ...
        'subject_notes', '', ...
        'subject_ts', '2020-08-18 23:34:35');

    entry_output10 = struct(...
        'subject_id', 'm3', ...
        'dob', '2020-08-05', ...
        'sex', 'U', ...
        'species', 'mouse', ...
        'mark_type', 'ear', ...
        'source_name', 'homemade', ...
        'strain_name', 'jRGECO', ...
        'subject_ts', '2020-08-18 23:34:35');
    
    entry_output11 = struct(...
        'subject_id', 'm3', ...
        'dob', '2020-08-05', ...
        'sex', 'U', ...
        'species', 'mouse', ...
        'breeding_pair', '', ...
        'mark_type', 'ear', ...
        'mark', '', ...
        'source_name', 'homemade', ...
        'strain_name', 'jRGECO', ...
        'subject_notes', '', ...
        'subject_ts', '2020-08-18 23:34:35');
    
    entry_input2 = struct(...
        'subject_id', 'm3', ...
        'dob', datetime(2020, 8, 5), ...
        'sex', 'U', ...
        'breeding_pair', '', ...
        'species', 'mouse', ...
        'mark_type', 'ear', ...
        'mark', '', ...
        'source_name', 'homemade', ...
        'strain_name', 'jRGECO', ...
        'subject_notes', '', ...
        'subject_ts', '');
    
    entry_output21 = struct(...
        'subject_id', 'm3', ...
        'dob', '2020-08-05', ...
        'sex', 'U', ...
        'breeding_pair', '', ...
        'species', 'mouse', ...
        'mark_type', 'ear', ...
        'mark', '', ...
        'source_name', 'homemade', ...
        'strain_name', 'jRGECO', ...
        'subject_notes', '', ...
        'subject_ts', datestr(datetime('now'), 'yyyy-mm-dd HH:MM:ss'));
    

    if isequal(gui_utils.cleanupEntry(entry_input1), entry_output10)
        disp 'passed for clean empty field test with argument entry'
    else
        disp 'failed for clean empty field test with argument entry'
        gui_utils.cleanupEntry(entry_input1)
        entry_output10
    end
    
    if isequal(gui_utils.cleanupEntry(entry_input1, table), entry_output11)
        disp 'passed for insert default test with arguments entry and table'
     else
        disp 'failed for insert default test with arguments entry and table'
        gui_utils.cleanupEntry(entry_input1)
        entry_output11
    end  
    
    if isequal(gui_utils.cleanupEntry(entry_input2, table), entry_output21)
        disp 'passed for converting datetime to str'
     else
        disp 'failed for converting datetime to str'
        gui_utils.cleanupEntry(entry_input2)
        entry_output21
    end
    
    